# Generated by Django 3.2.5 on 2022-01-12 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('scale', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mid', models.CharField(max_length=200, unique=True)),
                ('material', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(default='None', max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.scale')),
            ],
        ),
    ]
