# Generated by Django 3.2.5 on 2022-01-14 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.TextField(max_length=200)),
                ('supplier_address', models.TextField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='scale',
            new_name='scaleid',
        ),
        migrations.RenameField(
            model_name='scale',
            old_name='uid',
            new_name='scaleid',
        ),
        migrations.AddField(
            model_name='material',
            name='suupplierid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
