# Generated by Django 3.2.5 on 2022-01-22 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_material_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mid', models.CharField(max_length=200, unique=True)),
                ('material', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(default='None', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('scaleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.scale')),
                ('suupplierid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
