# Generated by Django 3.2.5 on 2022-01-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_auto_20220122_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
