# Generated by Django 3.2.5 on 2022-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_auto_20220122_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(),
        ),
    ]
