# Generated by Django 3.2.5 on 2022-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_alter_material_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='mid',
            field=models.CharField(max_length=200),
        ),
    ]
