# Generated by Django 4.0 on 2022-01-23 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_alter_materialtransaction_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
