# Generated by Django 4.0 on 2022-01-24 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_materialtransaction_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotationAmount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(max_length=1000, unique=True)),
                ('gross_amount', models.FloatField()),
                ('vat', models.IntegerField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='quotationclient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('clientname', models.CharField(default='None', max_length=500)),
                ('clientaddress', models.TextField(default='None', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='quotationitem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(default='None', max_length=300, unique=True)),
                ('unit_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='quotationNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(default='0650', max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='quotationsize',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('size', models.CharField(default='None', max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('goods_description', models.TextField(default='None', max_length=1000)),
                ('quantity', models.IntegerField(default=1, max_length=20000)),
                ('date', models.DateField()),
                ('total_price', models.FloatField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.quotationclient')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.quotationitem')),
                ('quotation_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.quotationnumber')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.quotationsize')),
            ],
        ),
    ]
