# Generated by Django 3.2.5 on 2022-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_demo_alter_quotation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.IntegerField(),
        ),
    ]
