# Generated by Django 4.0 on 2022-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_alter_demo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
