# Generated by Django 4.0 on 2022-01-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_quotation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
