# Generated by Django 4.0 on 2022-01-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_remove_quotationitem_unit_price_quotation_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='goods_description',
            field=models.TextField(max_length=1000),
        ),
    ]
