# Generated by Django 3.2.5 on 2022-01-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0020_quotationnumber_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationnumber',
            name='clientaddress',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quotationnumber',
            name='clientname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quotationnumber',
            name='quotation_number',
            field=models.IntegerField(),
        ),
    ]
