# Generated by Django 3.2.5 on 2022-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0021_auto_20220127_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationnumber',
            name='quotation_number',
            field=models.IntegerField(unique=True),
        ),
    ]
